#!/bin/bash

user=$(whoami)
host=$(cat /proc/sys/kernel/hostname)
os='Arch, btw'
kernel=$(uname -r | cut -d'-' -f1)
type=$(uname -r | cut -d'-' -f2)
shell=$(echo $SHELL | awk '{ print substr ( $0, 6 ) }')
uptime=$(uptime -p | awk '{ print substr ( $0, 4 ) }')
packages=$(pacman -Qq | wc -l)

# echo -e '\033[35m\033[1m'${user^}'\033[0m'@'\033[36m\033[1m'${host^}
echo -e '\033[31m\033[1mOS        →\033[0m  \e[3m'$os
echo -e '\e[23m\033[32m\033[1mKERNEL    →\033[0m  \e[3m'$kernel $type
echo -e '\e[23m\033[33m\033[1mSHELL     →\033[0m  \e[3m'${shell^}
echo -e '\e[23m\033[34m\033[1mUPTIME    →\033[0m  \e[3m'$uptime'\e[23m'
echo -e '\e[23m\033[35m\033[1mPACKAGES  →\033[0m  \e[3m'$packages'\e[23m'
